### ISSUE TITLE
For some reason it stopped working

### ISSUE THREAD

**Issue by TourTerrible** [valeriangalliat/spotify-buddylist#3]
It just returns empty result now and I am not able to figure out what's wrong!

```
{
  "friends": []
}
```

**Comment by valeriangalliat** [comment]
Yeap I noticed something similar since a few months, I don't get an empty list but some entries are gone.

I thought it was a change on Spotify side where they returned only the friends that ALSO followed me (not just every random profile I follow) for privacy or something but I did a few tests and it doesn't appear to be the case.

What I could confirm though is that those profiles are also gone from the the "friend activity" list on the official desktop app, so at that point I definitely can't do anything. :(

**Comment by TourTerrible** [comment]
Yep, I noticed this too. 
But for a few days, I am getting an empty list. I checked the desktop app and found that the list is getting shorter day by day, I used to get 10+ friends earlier, now just 3, and I guess it is cache or previously stored data that will eventually fade out resulting in an empty list on the desktop app too. Spotify just changed something I wonder where they are going with this.
